spring:
  application:
    name: my-market-app

  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: DEBUG
    org.springframework.web.bind: DEBUG
    org.springframework.web.method.support.InvocableHandlerMethod: DEBUG