services:
  postgres-db:
    image: postgres:16-alpine
    container_name: my-postgres-db
    env_file: .env
    ports:
      - "${POSTGRES_OUTER_PORT}:5432"
    volumes:
      - ./postgres-db/init/:/docker-entrypoint-initdb.d
      - my-market-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-market-network

  redis-cache:
    image: redis:7.4.2-bookworm
    container_name: my-redis-cache
    env_file: .env
    restart: always
    ports:
      - "${REDIS_OUTER_PORT}:6379"
    volumes:
      - my-market-data:/var/lib/redis/data
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-market-network

  my-market-app:
    build:
      context: .
      dockerfile: ./market-app/Dockerfile
    container_name: my-market-app
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres-db:${POSTGRES_OUTER_PORT}/${MARKET_APP_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${MARKET_APP_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARKET_APP_POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${MARKET_APP_SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${MARKET_APP_SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      PAYMENT_SERVICE_BASE_URL: http://my-payment-service:8080
      KC_OUTER_REALM_URI: http://localhost:${KC_OUTER_PORT}/realms/nesterukia-realm
      KC_INNER_REALM_URI: http://keycloak-sso:8080/realms/nesterukia-realm
    ports:
      - "${MARKET_APP_OUTER_PORT}:8080"
    networks:
      - my-market-network
    restart: on-failure

  my-payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: my-payment-service
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: r2dbc:postgresql://postgres-db:${POSTGRES_OUTER_PORT}/${PAYMENT_SERVICE_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${PAYMENT_SERVICE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${PAYMENT_SERVICE_POSTGRES_PASSWORD}
      KC_OUTER_REALM_URI: http://localhost:${KC_OUTER_PORT}/realms/nesterukia-realm
      KC_INNER_REALM_URI: http://keycloak-sso:8080/realms/nesterukia-realm
    ports:
      - "${PAYMENT_SERVICE_OUTER_PORT}:8080"
    networks:
      - my-market-network
    restart: on-failure

  keycloak-sso:
    image: quay.io/keycloak/keycloak:latest
    container_name: my-keycloak-sso
    command: "start-dev --import-realm"
    env_file: .env
    environment:
      KC_DB_URL: jdbc:postgresql://postgres-db:${POSTGRES_OUTER_PORT}/${KC_DB_NAME}
      KC_HOSTNAME: http://localhost:${KC_OUTER_PORT}
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./keycloak/nesterukia-realm.json:/opt/keycloak/data/import/nesterukia-realm-realm.json
      - my-market-data:/var/lib/postgresql/data
    networks:
      - my-market-network
    restart: on-failure

  nginx-gateway:
    image: nginx:alpine
    container_name: my-nginx-gateway
    ports:
      - "${KC_OUTER_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - keycloak-sso
    networks:
      - my-market-network
    restart: on-failure

volumes:
  my-market-data:

networks:
  my-market-network:
    driver: bridge