services:
  postgres-db:
    image: postgres:16-alpine
    container_name: my-market-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - my-market-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-market-network

  redis-cache:
    image: redis:7.4.2-bookworm
    container_name: my-redis-cache
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - my-market-data:/var/lib/redis/data
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my-market-network

  my-market-app:
    build:
      context: .
      dockerfile: ./market-app/Dockerfile
    container_name: my-market-app
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - my-market-network
    restart: on-failure

volumes:
  my-market-data:

networks:
  my-market-network:
    driver: bridge