events {
    worker_connections 1024;
}

http {
    upstream keycloak {
        server keycloak-sso:8080;
    }

    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://keycloak;
            proxy_set_header Host localhost:8380;
            proxy_set_header X-Forwarded-Host localhost:8380;
            proxy_set_header X-Forwarded-Port 8380;
            proxy_set_header X-Forwarded-Proto http;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
