#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$MARKET_APP_POSTGRES_USER" WITH PASSWORD '$MARKET_APP_POSTGRES_PASSWORD';
    CREATE DATABASE "$MARKET_APP_POSTGRES_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$MARKET_APP_POSTGRES_DB" TO "$MARKET_APP_POSTGRES_USER";

    \c "$MARKET_APP_POSTGRES_DB"
    GRANT ALL ON SCHEMA public TO "$MARKET_APP_POSTGRES_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$MARKET_APP_POSTGRES_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$MARKET_APP_POSTGRES_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$PAYMENT_SERVICE_POSTGRES_USER" WITH PASSWORD '$PAYMENT_SERVICE_POSTGRES_PASSWORD';
    CREATE DATABASE "$PAYMENT_SERVICE_POSTGRES_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$PAYMENT_SERVICE_POSTGRES_DB" TO "$PAYMENT_SERVICE_POSTGRES_USER";

    \c "$PAYMENT_SERVICE_POSTGRES_DB"
    GRANT ALL ON SCHEMA public TO "$PAYMENT_SERVICE_POSTGRES_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$PAYMENT_SERVICE_POSTGRES_USER";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$PAYMENT_SERVICE_POSTGRES_USER";
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER "$KC_DB_USERNAME" WITH PASSWORD '$KC_DB_PASSWORD';
    CREATE DATABASE "$KC_DB_NAME";
    GRANT ALL PRIVILEGES ON DATABASE "$KC_DB_NAME" TO "$KC_DB_USERNAME";

    \c "$KC_DB_NAME"
    GRANT ALL ON SCHEMA public TO "$KC_DB_USERNAME";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$KC_DB_USERNAME";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$KC_DB_USERNAME";
EOSQL
